config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :maintenances
  resources :houses do
    resources :maintenances, only: [:new, :create]
    resources :expenses
  end

  get "api/houses", to: "api/houses#index"
  get "api/houses/:id", to: "api/houses#show"
  post "api/houses", to: "api/houses#create"
  post "api/houses/:id", to: "api/houses#update"
  delete "api/houses/:id", to: "api/houses#destroy"

  get "maintenances/new", to: "maintenances#new"
  post "maintenances", to: "maintenances#create"
  get "houses/:id/maintenances", to: "maintenances#index"
  get "houses/:id/maintenances/:id", to: "maintenances#show"

  get "expenses/new", to: "expenses#new"
  post "expenses", to: "expenses#create"
  get "houses/:id/expenses/:id", to: "expenses#show"
  get "houses/:id/expenses", to: "expenses#index"
  # patch "houses/:id/expenses/:id/edit", to: "expenses#edit"

  get "users/show", to: "users#show"
end

app/controllers/api/houses_controller.rb
module Api
  class HousesController  < ActionController::API
    def index
      @houses = House.all
      render json: @houses
    end

    def show
      @house = House.find(params[:id])
      render json: @house
    end

    def create
      @house = House.new(house_params)
      if @house.save
        render json: @house
      else
        render status: :unprocessable_entity
      end
    end

    def update
      @house = House.find(params[:id])
      if @house.update(house_params)
        render json: @house
      else
        render status: :unprocessable_entity
      end
    end

    def destroy
      @house = House.find(params[:id])
      if @house.destroy
        render json: @house
      else
        render status: :unprocessable_entity
      end
    end

    private

  def house_params
    params.require(:house).permit(
      :name,
      :address,
      :square_feet,
      :number_of_rooms,
      :number_of_bathrooms,
      :has_storm_shelter,
      :has_garage,
      :rental_amount,
      :has_gas,
      :is_occupied,
      :img_url,
      :longitude,
      :latitude,
      :user_id,
      photos: []
    )
  end
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def new
    @house = House.new
  end

  def create
    @house = House.new(house_params)
    @house.user_id = current_user.id

    if @house.save
      redirect_to house_path(@house), notice: "House was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @houses = House.all
    @markers = @houses.geocoded.map do |house|
      {
        lat: house.latitude,
        lng: house.longitude
      }
    end
  end

  def show
    @house = House.find(params[:id])
    handle_missing_image if @house.photos.blank?
    @markers = [{
      lng: @house.longitude,
      lat: @house.latitude,
      info_window_html: render_to_string(partial: "info_window", locals: { house: @house })
    }]
  end

  def edit
    @house = House.find(params[:id])
  end

  def update
    @house = House.find(params[:id])
    if @house.update(house_params)
      redirect_to house_path(@house)
    else
      render 'edit'
    end
  end

  def destroy
    @house = House.find(params[:id])
    if @house.destroy
      redirect_to root_path
    else
      render 'show'
    end
  end

  private

  def house_params
    params.require(:house).permit(
      :name,
      :address,
      :square_feet,
      :number_of_rooms,
      :number_of_bathrooms,
      :has_storm_shelter,
      :has_garage,
      :rental_amount,
      :has_gas,
      :is_occupied,
      :img_url,
      :longitude,
      :latitude,
      :user_id,
      photos: []
    )
  end

  def find_house_or_redirect
    House.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "House not found"
    redirect_to houses_path
    nil
  end

  def handle_missing_image
    return if @house.photos.attached?

    flash[:error] = "Image not found for this house."
    redirect_to houses_path
    true
  end
end

app/views/houses/_form.html.erb
<%= simple_form_for @house do |f| %>
  <%= f.input :address, input_html: { data: { address_autocomplete_target: "address" }, class: "d-none" },
                        wrapper_html: { data: { controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] } }
                        %>
                        <% end %>

app/views/houses/_info_window.html.erb
<div>
  <div>
    <h2><%= house.name %></h2>
  </div>
  <div>
    <p><%= house.address %></p>
  </div>
</div>

app/views/houses/_marker.html.erb
<%# <%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %> %>

app/views/houses/edit.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="form-container p-4 shadow rounded">
        <%= form_with model: @house do |f| %>
          <div class="form-container">
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :address %>
              <%= f.text_field :address, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :square_feet %>
              <%= f.number_field :square_feet, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :has_garage, class: "form-check-label" %>
              <%= f.check_box :has_garage, class: "form-check-input" %>
            </div>

            <div class="form-group">
              <%= f.label :number_of_rooms %>
              <%= f.number_field :number_of_rooms, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :number_of_bathrooms %>
              <%= f.number_field :number_of_bathrooms, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :has_storm_shelter, class: "form-check-label" %>
              <%= f.check_box :has_storm_shelter, class: "form-check-input" %>
            </div>

            <div class="form-group">
              <%= f.label :rental_amount %>
              <%= f.number_field :rental_amount, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :has_gas, class: "form-check-label" %>
              <%= f.check_box :has_gas, class: "form-check-input" %>
            </div>

            <div class="form-group">
              <%= f.label :is_occupied, class: "form-check-label" %>
              <%= f.check_box :is_occupied, class: "form-check-input" %>
            </div>

            <div>
              <%= f.label :photo %>
              <%= f.file_field :photo %>
            </div>
            
          </div>
          <div class="d-flex justify-content-between">
            <div class="">
              <%= link_to "Cancel", root_path, class: "btn btn-secondary" %>
            </div>
            <div class="">
              <%= f.submit "Submit", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/houses/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-7">
      <% @houses.each do |house| %>
        <a href="<%= house_path(house) %>" class="card-link" style="text-decoration: none;">
          <div class="card mb-4" style="border: none; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); overflow: hidden;">
            <div class="card-body">
              <div class="text-center">
                <div class="image-container" style="width: 100%; height: 400px; display: flex; align-items: center; justify-content: center; overflow: hidden;">
                  <% if house.photos.attached? && house.photos.any? %>
                    <%= cl_image_tag house.photos.first.key, class: "card-image", style: "object-fit: cover; max-width: 100%; max-height: 100%;" %>
                  <% end %>
                </div>
                <div>
                  <h2 class="card-title no-underline"><%= house.name %></h2>
                  <p class="info-line no-underline">
                    <span class="no-underline"><%= house.number_of_rooms %> bds</span> |
                    <span class="no-underline"><%= house.number_of_bathrooms %> ba</span> |
                    <span class="no-underline"><%= house.square_feet %> sqft</span>
                  </p>
                  <p class="card-text no-underline"><%= house.address %></p>
                </div>
              </div>
            </div>
          </div>
        </a>
      <% end %>
    </div>
    <div class="col-12 col-lg-5">
      <div class="card rounded shadow"
        id="mapbox" style="width: 100%; height: 810px; position: sticky; top: 0;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/houses/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="form-container p-4 shadow rounded">
        <%= simple_form_for @house do |f| %>
          <div class="form-container">
            <%= f.input :name, label: "Name", required: true %>

            <%= f.input :square_feet, class: "form-control", label: "Square Feet", required: true %>

            <%= f.input :address, input: "Address", required: true %>
            <%= f.input :rental_amount, class: "form-control", required: true %>
            <%= f.input :number_of_rooms, class: "form-control", required: true %>
            <%= f.input :number_of_bathrooms, label: "Bathrooms", class: "form-control", required: true %>
            <div class="row">
              <%= f.label :has_garage, class: "form-check-label" %>
              <%= f.check_box :has_garage, class: "form-check-input", label: "Garage?" %>

              <%= f.label :has_storm_shelter, class: "form-check-label" %>
              <%= f.check_box :has_storm_shelter, class: "form-check-input" %>

              <%= f.label :has_gas, class: "form-check-label" %>
              <%= f.check_box :has_gas, class: "form-check-input", label: "Has gas" %>

              <%= f.label :is_occupied, class: "form-check-label" %>
              <%= f.check_box :is_occupied, class: "form-check-input" %>
            </div>
            <%= f.input :photos, as: :file, class: "mb-4", input_html: { multiple: true }, required: true %>
          </div>
          <div class="d-flex justify-content-between">
            <div>
              <%= link_to "Cancel", root_path, class: "btn btn-secondary" %>
            </div>
            <div>
              <%= f.submit "Submit", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/houses/show.html.erb
<!--`
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-8">
      <div class="card rounded shadow">`
        <% @house.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 400, width: 854, crop: :fill %>
        <% end %>
        <h2><%= @house.name %></h2>
        <p><%= @house.address %></p>
        <p><%= @house.square_feet %></p>
        <p><%= @house.number_of_rooms %></p>
        <div class="button-container mt-3 mb-2">
          <%= link_to "Edit", edit_house_path(@house), class: "btn btn-primary" %>
          <%= link_to "Maintenance Tickets", maintenances_path(house_id: @house) %>
          <%= link_to "Delete", house_path(@house), class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <%= link_to "Create maint ticket", new_house_maintenance_path(@house.id), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-4">
      <div class="card rounded shadow"
          id="mapbox" style="width: 100%; height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>
-->
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-8">
      <div class="card rounded shadow">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <% @house.photos.each_with_index do |photo, index| %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= index.zero? ? 'active' : '' %>"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <% @house.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
                <%= cl_image_tag photo.key, class: "d-block w-100", height: 400, width: 854, crop: :fill, alt: "House Photo" %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <h2><%= @house.name %></h2>
        <p><%= @house.address %></p>
        <p><%= @house.square_feet %></p>
        <p><%= @house.number_of_rooms %></p>
        <div class="button-container mt-3 mb-2">
          <%= link_to "Edit", edit_house_path(@house), class: "btn btn-secondary" %>
          <%= link_to "Maintenance Tickets", maintenances_path(house_id: @house) %>
          <%= link_to "Delete", house_path(@house), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <%= link_to "Expenses", house_expenses_path(@house) %>
          <%= link_to "Create maint ticket", new_house_maintenance_path(@house.id), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-4">
      <div class="card rounded shadow"
          id="mapbox" style="width: 100%; height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>