config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :maintenances
  resources :houses do
    resources :maintenances, only: [:new, :create]
    resources :expenses
  end

  get "api/houses", to: "api/houses#index"
  get "api/houses/:id", to: "api/houses#show"
  post "api/houses", to: "api/houses#create"
  post "api/houses/:id", to: "api/houses#update"
  delete "api/houses/:id", to: "api/houses#destroy"

  get "maintenances/new", to: "maintenances#new"
  post "maintenances", to: "maintenances#create"
  get "houses/:id/maintenances", to: "maintenances#index"
  get "houses/:id/maintenances/:id", to: "maintenances#show"

  get "expenses/new", to: "expenses#new"
  post "expenses", to: "expenses#create"
  get "houses/:id/expenses/:id", to: "expenses#show"
  get "houses/:id/expenses", to: "expenses#index"
  # patch "houses/:id/expenses/:id/edit", to: "expenses#edit"

  get "users/show", to: "users#show"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to new_house_path, class: "nav-link" do %>
              <i class="fa-sharp fa-regular fa-plus fa-lg"></i> New house
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "salim.JPG", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Add expense", expenses_new_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>