config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :maintenances
  resources :houses do
    resources :maintenances, only: [:new, :create]
    resources :expenses
  end

  get "api/houses", to: "api/houses#index"
  get "api/houses/:id", to: "api/houses#show"
  post "api/houses", to: "api/houses#create"
  post "api/houses/:id", to: "api/houses#update"
  delete "api/houses/:id", to: "api/houses#destroy"

  get "maintenances/new", to: "maintenances#new"
  post "maintenances", to: "maintenances#create"
  get "houses/:id/maintenances", to: "maintenances#index"
  get "houses/:id/maintenances/:id", to: "maintenances#show"

  get "expenses/new", to: "expenses#new"
  post "expenses", to: "expenses#create"
  get "houses/:id/expenses/:id", to: "expenses#show"
  get "houses/:id/expenses", to: "expenses#index"
  # patch "houses/:id/expenses/:id/edit", to: "expenses#edit"

  get "users/show", to: "users#show"
end

app/models/maintenance.rb
class Maintenance < ApplicationRecord
  belongs_to :house
  has_many_attached :photos

  validates :title, presence: true
  validates :description, presence: true
  validates :photos, presence: true
end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController
  before_action :set_house, only: %i[new create]

  def new
    @maintenance = Maintenance.new
  end

  def create
    @maintenance = Maintenance.new(maintenance_params)
    @maintenance.house = @house
    @maintenance.user_id = current_user.id
    if @maintenance.save
      redirect_to house_path(@house), notice: "Maintenance ticket was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    if params[:house_id].present? && House.exists?(params[:house_id])
      house = House.find(params[:house_id])
      @maintenances = house.maintenances
    else
      flash[:error] = "House not found."
      render "errors/error", status: :not_found
    end
  end

  def show
    @maintenance = Maintenance.find(params[:id])
  end

  private

  def set_house
    @house = House.find(params[:house_id])
  end

  def maintenance_params
    params.require(:maintenance).permit(
      :house_id,
      :user_id,
      :title,
      :description,
      :time_stamp,
      :created_at,
      :updated_at,
      photos: []
    )
  end
end

app/views/maintenances/index.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="text-center">
        <% if @maintenances.any? %>
          <% @maintenances.each do |maintenance| %>
            <a href="<%= maintenance_path(maintenance) %>">
              <div class="card mb-3">
                <div class="card-body">
                  <h5 class="card-title"><%= maintenance.title %></h5>
                  <% if maintenance.photos.attached? %>
                    <% maintenance.photos.each do |photo| %>
                      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill, class: "img-fluid" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </a>
          <% end %>
        <% else %>
          <h4>No maintenance tickets created for this house yet.</h4>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/maintenances/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="form-container p-4 shadow rounded">
        <h1>Create a maintenance ticket for <%= @house.name %></h1>
        <%= simple_form_for([@house, @maintenance]) do |f| %>
          <div class="form-container">
            <%= f.input :title, label: "Title", required: true %>
            <%= f.input :description, label: "Description", required: true %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          </div>
          <div class="d-flex justify-content-between">
            <div>
              <%= link_to "Cancel", house_path(@house), class: "btn btn-secondary" %>
            </div>
            <div>
              <%= f.submit "Create Maintenance Ticket", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/maintenances/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="form-container p-4 shadow rounded">
        <div>
          <h4>
            <%= @maintenance.title %>
          </h4>
        </div>
        <div>
          <h5>
            <%= @maintenance.description %>
          </h5>
        </div>
        <div>
          <% if @maintenance.photos.attached? %>
          <% @maintenance.photos.each do |photo| %>
            <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>